### ISSUE TITLE
Question about GitHub CoPilot????????!1111!!!!

### ISSUE THREAD

**Issue by yrikhn** [Oliverach/TicTacToe#2]
helo frend
my question was if is combatiple with github copilot ai automation code writing tool of github?
please answer we need for our company in pakistan to make better supply of JSON Objects

**Comment by Oliverach** [comment]
https://www.youtube.com/watch?v=xm3YgoEiEDc

**Comment by yrikhn** [comment]
wat is rick astley?? he developed github copilot? give clear answer sir!!!!!!!!

**Comment by Oliverach** [comment]
https://www.youtube.com/watch?v=rAG4nq8FwJc
